### ISSUE TITLE
Enable install from broadcom repos for Suse

### ISSUE THREAD

**Issue by jeff350** [saltstack/salt-bootstrap#2063]
### Description of Issue/Question

Currently salt bootstrap only supports installing from the upstream SUSE repos, however only 3006.0 is available in these repos. given that the new bradcom repos are generic rpms they can be used to install the current versions on suse. see this PR for a tested version of how the repos can be used for suse https://github.com/saltstack/salt-install-guide/pull/14.

The saltstack formulas teams uses the bootstrap script to build our test containers. Having to bootstrap script support installing the latest version from the salt repos would better allow us to test the formulas. 

Before I start on a PR I would like input on how this change should be made. Should the bootstrap support both the Suse repos and salt repo or just the salt repo?

### Setup
Spin up suse container of your choice:
- sudo docker run -it opensuse/tumbleweed /bin/sh
- sudo docker run -it opensuse/leap:15.5 /bin/sh
- sudo docker run -it opensuse/leap:15.6 /bin/sh

Running the install command `sh bootstrap-salt.sh -D stable` the latest stable release is expected to be installed, 3006.9. however 3006.0 is installed from the SUSE repos.

### Steps to Reproduce Issue

```
1. zypper search salt-minion
2. zypper info salt-minion
3. zypper install awk
4. curl -o bootstrap-salt.sh -L https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh
5. sh bootstrap-salt.sh -D stable
6. salt-minion --version
7. sh bootstrap-salt.sh -v
```

leap:15.5:
```
sh-4.4# zypper search salt-minion
Retrieving repository 'Update repository of openSUSE Backports' metadata .............................................................[done]
Building repository 'Update repository of openSUSE Backports' cache ..................................................................[done]
Retrieving repository 'Non-OSS Repository' metadata ..................................................................................[done]
Building repository 'Non-OSS Repository' cache .......................................................................................[done]
Retrieving repository 'Open H.264 Codec (openSUSE Leap)' metadata ....................................................................[done]
Building repository 'Open H.264 Codec (openSUSE Leap)' cache .........................................................................[done]
Retrieving repository 'Main Repository' metadata .....................................................................................[done]
Building repository 'Main Repository' cache ..........................................................................................[done]
Retrieving repository 'Update repository with updates from SUSE Linux Enterprise 15' metadata ........................................[done]
Building repository 'Update repository with updates from SUSE Linux Enterprise 15' cache .............................................[done]
Retrieving repository 'Main Update Repository' metadata ..............................................................................[done]
Building repository 'Main Update Repository' cache ...................................................................................[done]
Retrieving repository 'Update Repository (Non-Oss)' metadata .........................................................................[done]
Building repository 'Update Repository (Non-Oss)' cache ..............................................................................[done]
Loading repository data...
Reading installed packages...

S  | Name                      | Summary                                      | Type
---+---------------------------+----------------------------------------------+--------
   | open-vm-tools-salt-minion | Script file to install/uninstall salt-minion | package
   | salt-minion               | The client component for Saltstack           | package
sh-4.4# zypper info salt-minion
Loading repository data...
Reading installed packages...


Information for package salt-minion:
------------------------------------
Repository     : Update repository with updates from SUSE Linux Enterprise 15
Name           : salt-minion
Version        : 3006.0-150500.4.44.2
Arch           : x86_64
Vendor         : SUSE LLC <https://www.suse.com/>
Installed Size : 43.3 KiB
Installed      : No
Status         : not installed
Source package : salt-3006.0-150500.4.44.2.src
Upstream URL   : https://saltproject.io/
Summary        : The client component for Saltstack
Description    : 
    Salt minion is queried and controlled from the master.
    Listens to the salt master and execute the commands.

sh-4.4# curl -o bootstrap-salt.sh -L https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  296k  100  296k    0     0   525k      0 --:--:-- --:--:-- --:--:-- 1452k
sh-4.4# sh bootstrap-salt.sh -D stable
bootstrap-salt.sh: line 595: ps: command not found
 *  INFO: Running version: 2024.11.29
 *  INFO: Executed by: 
 *  INFO: Command line: 'bootstrap-salt.sh -D stable'
 * ERROR: systemctl: command not found, assume systemd not implemented, _SYSTEMD_FUNCTIONAL 0

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   6.1.0-28-amd64
 *  INFO:   Distribution: opensuse 15.5

 * DEBUG: Binaries will be searched using the following $PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 *  INFO: Installing minion
 *  INFO: Found function install_opensuse_15_onedir_deps
 * DEBUG: DEPS_INSTALL_FUNC=install_opensuse_15_onedir_deps
 * DEBUG: config_opensuse_15_onedir_salt not found....
 * DEBUG: config_opensuse_15_5_onedir_salt not found....
 * DEBUG: config_opensuse_15_salt not found....
 * DEBUG: config_opensuse_15_5_salt not found....
 * DEBUG: config_opensuse_onedir_salt not found....
 * DEBUG: config_opensuse_salt not found....
 *  INFO: Found function config_salt
 * DEBUG: CONFIG_SALT_FUNC=config_salt
 * DEBUG: preseed_opensuse_15_onedir_master not found....
 * DEBUG: preseed_opensuse_15_5_onedir_master not found....
 * DEBUG: preseed_opensuse_15_master not found....
 * DEBUG: preseed_opensuse_15_5_master not found....
 * DEBUG: preseed_opensuse_onedir_master not found....
 * DEBUG: preseed_opensuse_master not found....
 *  INFO: Found function preseed_master
 * DEBUG: PRESEED_MASTER_FUNC=preseed_master
 * DEBUG: INSTALL_FUNC_NAMES=install_opensuse_15_onedir install_opensuse_15_5_onedir install_opensuse_onedir
 * DEBUG: install_opensuse_15_onedir not found....
 * DEBUG: install_opensuse_15_5_onedir not found....
 *  INFO: Found function install_opensuse_onedir
 * DEBUG: INSTALL_FUNC=install_opensuse_onedir
 * DEBUG: install_opensuse_15_onedir_post not found....
 * DEBUG: install_opensuse_15_5_onedir_post not found....
 * DEBUG: install_opensuse_15_post not found....
 * DEBUG: install_opensuse_15_5_post not found....
 *  INFO: Found function install_opensuse_onedir_post
 * DEBUG: POST_INSTALL_FUNC=install_opensuse_onedir_post
 * DEBUG: install_opensuse_15_onedir_restart_daemons not found....
 * DEBUG: install_opensuse_15_5_onedir_restart_daemons not found....
 * DEBUG: install_opensuse_15_restart_daemons not found....
 * DEBUG: install_opensuse_15_5_restart_daemons not found....
 * DEBUG: install_opensuse_onedir_restart_daemons not found....
 *  INFO: Found function install_opensuse_restart_daemons
 * DEBUG: STARTDAEMONS_INSTALL_FUNC=install_opensuse_restart_daemons
 * DEBUG: daemons_running_opensuse_15_onedir not found....
 * DEBUG: daemons_running_opensuse_15_5_onedir not found....
 * DEBUG: daemons_running_opensuse_15 not found....
 * DEBUG: daemons_running_opensuse_15_5 not found....
 * DEBUG: daemons_running_opensuse_onedir not found....
 * DEBUG: daemons_running_opensuse not found....
 *  INFO: Found function daemons_running_onedir
 * DEBUG: DAEMONS_RUNNING_FUNC=daemons_running_onedir
 * DEBUG: install_opensuse_15_onedir_check_services not found....
 * DEBUG: install_opensuse_15_5_onedir_check_services not found....
 * DEBUG: install_opensuse_15_check_services not found....
 * DEBUG: install_opensuse_15_5_check_services not found....
 * DEBUG: install_opensuse_onedir_check_services not found....
 *  INFO: Found function install_opensuse_check_services
 * DEBUG: CHECK_SERVICES_FUNC=install_opensuse_check_services
 *  INFO: Running install_opensuse_15_onedir_deps()
bootstrap-salt.sh: line 6680: pgrep: command not found
bootstrap-salt.sh: line 6680: pgrep: command not found
Adding repository 'Salt configuration management for openSUSE (15.5)' [.....done]
Repository 'Salt configuration management for openSUSE (15.5)' successfully added

URI         : https://download.opensuse.org/repositories/systemsmanagement:/saltstack/15.5/
Enabled     : Yes
GPG Check   : Yes
Autorefresh : Yes
Priority    : 99 (default priority)

Repository priorities are without effect. All enabled repositories share the same priority.
bootstrap-salt.sh: line 6680: pgrep: command not found
Repository 'Update repository of openSUSE Backports' is up to date.
Repository 'Non-OSS Repository' is up to date.
Repository 'Open H.264 Codec (openSUSE Leap)' is up to date.
Repository 'Main Repository' is up to date.
Repository 'Update repository with updates from SUSE Linux Enterprise 15' is up to date.
Repository 'Main Update Repository' is up to date.
Repository 'Update Repository (Non-Oss)' is up to date.
Retrieving repository 'Salt configuration management for openSUSE (15.5)' metadata [.......

Automatically importing the following key:

  Repository:       Salt configuration management for openSUSE (15.5)
  Key Fingerprint:  50E6 0431 5448 5D99 0732 B5D6 ACAA 9CF7 E6E5 A213
  Key Name:         systemsmanagement OBS Project <systemsmanagement@build.opensuse.org>
  Key Algorithm:    RSA 2048
  Key Created:      Wed Dec  6 09:36:19 2023
  Key Expires:      Fri Feb 13 09:36:19 2026
  Rpm Name:         gpg-pubkey-e6e5a213-65704093



    Note: A GPG pubkey is clearly identified by its fingerprint. Do not rely on the key's name. If
    you are not sure whether the presented key is authentic, ask the repository provider or check
    their web site. Many providers maintain a web page showing the fingerprints of the GPG keys they
    are using.
..done]
Building repository 'Salt configuration management for openSUSE (15.5)' cache [....done]
All repositories have been refreshed.
 *  INFO: Running install_opensuse_onedir()
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 4 NEW packages are going to be installed:
  libdb-4_8 libpython2_7-1_0 python python-base

4 new packages to install.

Package download size:     7.6 MiB

Package install size change:
              |      30.4 MiB  required by to be installed packages
    30.4 MiB  |  -      0 B    released by to be removed packages

Backend:  classic_rpmtrans
Continue? [y/n/v/...? shows all options] (y): y
Retrieving: libdb-4_8-4.8.30-150000.7.9.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (1/4), 693.3 KiB    
Retrieving: libdb-4_8-4.8.30-150000.7.9.1.x86_64.rpm [.....done (3.7 MiB/s)]
Retrieving: libpython2_7-1_0-2.7.18-150000.68.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (2/4), 843.1 KiB    
Retrieving: libpython2_7-1_0-2.7.18-150000.68.1.x86_64.rpm [..........done (607.6 KiB/s)]
Retrieving: python-base-2.7.18-150000.68.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (3/4),   5.8 MiB    
Retrieving: python-base-2.7.18-150000.68.1.x86_64.rpm [........done (7.2 MiB/s)]
Retrieving: python-2.7.18-150000.68.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (4/4), 341.0 KiB    
Retrieving: python-2.7.18-150000.68.1.x86_64.rpm [....done]

Checking for file conflicts: [...done]
(1/4) Installing: libdb-4_8-4.8.30-150000.7.9.1.x86_64 [...done]
(2/4) Installing: libpython2_7-1_0-2.7.18-150000.68.1.x86_64 [...done]
(3/4) Installing: python-base-2.7.18-150000.68.1.x86_64 [................done]
(4/4) Installing: python-2.7.18-150000.68.1.x86_64 [..done]
bootstrap-salt.sh: line 6669: python3: command not found
bootstrap-salt.sh: line 6680: pgrep: command not found
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 83 NEW packages are going to be installed:
  busybox busybox-xz dbus-1 file iproute2 iputils kbd kbd-legacy libapparmor1 libargon2-1 libcryptsetup12 libcryptsetup12-hmac libdbus-1-3 libdevmapper1_03 libexpat1 libip4tc2 libjson-c3 libkmod2 liblz4-1 libmnl0 libpgm-5_2-0 libprocps8 libpython3_6m1_0 libseccomp2 libsodium23 libsystemd0 libunwind libxtables12 libyaml-0-2 libzmq5 logrotate pam-config pkg-config procps python3 python3-Babel python3-Jinja2 python3-M2Crypto python3-MarkupSafe python3-PyYAML python3-apipkg python3-appdirs python3-asn1crypto python3-base python3-certifi python3-cffi python3-chardet python3-contextvars python3-cryptography python3-distro python3-idna python3-immutables python3-iniconfig python3-jmespath python3-looseversion python3-msgpack python3-ordered-set python3-packaging python3-ply python3-psutil python3-py python3-pyOpenSSL python3-pyasn1 python3-pycparser python3-pyparsing python3-pytz python3-pyzmq python3-requests python3-rpm python3-salt python3-setuptools python3-simplejson python3-six python3-urllib3 python3-zypp-plugin salt salt-minion sudo systemd systemd-default-settings systemd-default-settings-branding-SLE systemd-presets-branding-MicroOS systemd-presets-common-SUSE

83 new packages to install.

Package download size:    40.8 MiB

Package install size change:
              |     166.1 MiB  required by to be installed packages
   166.1 MiB  |  -      0 B    released by to be removed packages

Backend:  classic_rpmtrans
Continue? [y/n/v/...? shows all options] (y): y
Retrieving: busybox-1.35.0-150500.8.2.x86_64 (Main Repository) (1/83), 601.3 KiB    
Retrieving: busybox-1.35.0-150500.8.2.x86_64.rpm [....done (520.6 KiB/s)]
Retrieving: file-5.32-7.14.1.x86_64 (Main Repository) (2/83),  50.0 KiB    
Retrieving: file-5.32-7.14.1.x86_64.rpm [...done (19.7 KiB/s)]
Retrieving: libargon2-1-0.0+git20171227.670229c-2.14.x86_64 (Main Repository) (3/83),  19.9 KiB    
Retrieving: libargon2-1-0.0+git20171227.670229c-2.14.x86_64.rpm [..done]
Retrieving: libip4tc2-1.8.7-1.1.x86_64 (Main Repository) (4/83),  24.0 KiB    
Retrieving: libip4tc2-1.8.7-1.1.x86_64.rpm [...done (18.3 KiB/s)]
Retrieving: libjson-c3-0.13-3.3.1.x86_64 (Main Repository) (5/83),  40.6 KiB    
Retrieving: libjson-c3-0.13-3.3.1.x86_64.rpm [..done]
Retrieving: libkmod2-29-4.15.1.x86_64 (Main Repository) (6/83),  56.9 KiB    
Retrieving: libkmod2-29-4.15.1.x86_64.rpm [...done (20.6 KiB/s)]
Retrieving: liblz4-1-1.9.3-150400.1.7.x86_64 (Main Repository) (7/83),  64.7 KiB    
Retrieving: liblz4-1-1.9.3-150400.1.7.x86_64.rpm [...done (3.6 KiB/s)]
Retrieving: libmnl0-1.0.4-1.25.x86_64 (Main Repository) (8/83),  16.4 KiB    
Retrieving: libmnl0-1.0.4-1.25.x86_64.rpm [..done]
Retrieving: libpgm-5_2-0-5.2.122-150400.15.6.x86_64 (Main Repository) (9/83), 167.6 KiB    
Retrieving: libpgm-5_2-0-5.2.122-150400.15.6.x86_64.rpm [...done (1.1 MiB/s)]
Retrieving: libseccomp2-2.5.3-150400.2.4.x86_64 (Main Repository) (10/83),  61.5 KiB    
Retrieving: libseccomp2-2.5.3-150400.2.4.x86_64.rpm [...done (33.8 KiB/s)]
Retrieving: libunwind-1.5.0-4.5.1.x86_64 (Main Repository) (11/83),  60.8 KiB    
Retrieving: libunwind-1.5.0-4.5.1.x86_64.rpm [...done (4.2 KiB/s)]
Retrieving: libxtables12-1.8.7-1.1.x86_64 (Main Repository) (12/83),  34.3 KiB    
Retrieving: libxtables12-1.8.7-1.1.x86_64.rpm [..done]
Retrieving: pkg-config-0.29.2-1.436.x86_64 (Main Repository) (13/83), 231.6 KiB    
Retrieving: pkg-config-0.29.2-1.436.x86_64.rpm [...done (841.9 KiB/s)]
Retrieving: iproute2-5.14-150400.1.8.x86_64 (Main Repository) (14/83), 1022.3 KiB    
Retrieving: iproute2-5.14-150400.1.8.x86_64.rpm [....done (5.2 MiB/s)]
Retrieving: iputils-20221126-150500.3.8.2.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (15/83), 128.8 KiB    
Retrieving: iputils-20221126-150500.3.8.2.x86_64.rpm [....done (154.0 KiB/s)]
Retrieving: kbd-legacy-2.4.0-150400.5.6.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (16/83), 538.5 KiB    
Retrieving: kbd-legacy-2.4.0-150400.5.6.1.noarch.rpm [...done (433.1 KiB/s)]
Retrieving: libapparmor1-3.0.4-150500.11.9.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (17/83),  74.8 KiB    
Retrieving: libapparmor1-3.0.4-150500.11.9.1.x86_64.rpm [...done (19.7 KiB/s)]
Retrieving: libdevmapper1_03-2.03.22_1.02.196-150500.7.12.2.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (18/83), 187.6 KiB    
Retrieving: libdevmapper1_03-2.03.22_1.02.196-150500.7.12.2.x86_64.rpm [....done (2.1 MiB/s)]
Retrieving: libexpat1-2.4.4-150400.3.25.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (19/83), 112.8 KiB    
Retrieving: libexpat1-2.4.4-150400.3.25.1.x86_64.rpm [..done (2.7 KiB/s)]
Retrieving: libsodium23-1.0.18-150000.4.8.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (20/83), 162.4 KiB    
Retrieving: libsodium23-1.0.18-150000.4.8.1.x86_64.rpm [..done (2.7 KiB/s)]
Retrieving: libyaml-0-2-0.1.7-150000.3.2.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (21/83),  50.2 KiB    
Retrieving: libyaml-0-2-0.1.7-150000.3.2.1.x86_64.rpm [...done]
Retrieving: pam-config-1.1-150200.3.9.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (22/83), 128.3 KiB    
Retrieving: pam-config-1.1-150200.3.9.1.x86_64.rpm [..done]
Retrieving: sudo-1.9.12p1-150500.7.10.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (23/83),   1.8 MiB    
Retrieving: sudo-1.9.12p1-150500.7.10.1.x86_64.rpm [...done (3.3 MiB/s)]
Retrieving: systemd-default-settings-branding-SLE-0.10-150300.3.7.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (24/83),  11.1 KiB    
Retrieving: systemd-default-settings-branding-SLE-0.10-150300.3.7.1.noarch.rpm [..done (11.1 KiB/s)]
Retrieving: systemd-default-settings-0.10-150300.3.7.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (25/83),  12.0 KiB    
Retrieving: systemd-default-settings-0.10-150300.3.7.1.noarch.rpm [..done (4.2 KiB/s)]
Retrieving: systemd-presets-common-SUSE-15-150500.20.6.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (26/83),  21.4 KiB    
Retrieving: systemd-presets-common-SUSE-15-150500.20.6.1.noarch.rpm [..done]
Retrieving: busybox-xz-1.35.0-150400.4.5.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (27/83),  10.5 KiB    
Retrieving: busybox-xz-1.35.0-150400.4.5.1.noarch.rpm [..done (10.5 KiB/s)]
Retrieving: libsystemd0-249.17-150400.8.43.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (28/83), 554.5 KiB    
Retrieving: libsystemd0-249.17-150400.8.43.1.x86_64.rpm [...done (2.3 MiB/s)]
Retrieving: kbd-2.4.0-150400.5.6.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (29/83),   1.8 MiB    
Retrieving: kbd-2.4.0-150400.5.6.1.x86_64.rpm [...done (3.3 MiB/s)]
Retrieving: libcryptsetup12-2.4.3-150400.3.3.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (30/83), 222.9 KiB    
Retrieving: libcryptsetup12-2.4.3-150400.3.3.1.x86_64.rpm [..done (2.8 KiB/s)]
Retrieving: libcryptsetup12-hmac-2.4.3-150400.3.3.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (31/83),  41.5 KiB    
Retrieving: libcryptsetup12-hmac-2.4.3-150400.3.3.1.x86_64.rpm [...done (21.1 KiB/s)]
Retrieving: python3-base-3.6.15-150300.10.75.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (32/83),   7.8 MiB    
Retrieving: python3-base-3.6.15-150300.10.75.1.x86_64.rpm [.....done (17.9 MiB/s)]
Retrieving: libpython3_6m1_0-3.6.15-150300.10.75.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (33/83),   1.2 MiB    
Retrieving: libpython3_6m1_0-3.6.15-150300.10.75.1.x86_64.rpm [..done (3.1 KiB/s)]
Retrieving: libprocps8-3.3.17-150000.7.39.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (34/83),  57.1 KiB    
Retrieving: libprocps8-3.3.17-150000.7.39.1.x86_64.rpm [...done (3.6 KiB/s)]
Retrieving: libdbus-1-3-1.12.2-150400.18.8.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (35/83), 151.4 KiB    
Retrieving: libdbus-1-3-1.12.2-150400.18.8.1.x86_64.rpm [..done (2.2 KiB/s)]
Retrieving: python3-3.6.15-150300.10.75.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (36/83), 102.2 KiB    
Retrieving: python3-3.6.15-150300.10.75.1.x86_64.rpm [..done (2.7 KiB/s)]
Retrieving: procps-3.3.17-150000.7.39.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (37/83), 277.9 KiB    
Retrieving: procps-3.3.17-150000.7.39.1.x86_64.rpm [...done (3.1 MiB/s)]
Retrieving: dbus-1-1.12.2-150400.18.8.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (38/83), 248.8 KiB    
Retrieving: dbus-1-1.12.2-150400.18.8.1.x86_64.rpm [...done (2.8 MiB/s)]
Retrieving: python3-zypp-plugin-0.6.4-150500.16.2.2.noarch (Update repository with updates from SUSE Linux Enterprise 15) (39/83),  12.2 KiB    
Retrieving: python3-zypp-plugin-0.6.4-150500.16.2.2.noarch.rpm [..done (12.2 KiB/s)]
Retrieving: python3-simplejson-3.17.2-150300.3.4.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (40/83),  73.2 KiB    
Retrieving: python3-simplejson-3.17.2-150300.3.4.1.x86_64.rpm [...done (21.2 KiB/s)]
Retrieving: python3-rpm-4.14.3-150400.59.16.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (41/83),  56.2 KiB    
Retrieving: python3-rpm-4.14.3-150400.59.16.1.x86_64.rpm [...done (12.7 KiB/s)]
Retrieving: python3-pyasn1-0.4.2-150000.3.5.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (42/83), 150.4 KiB    
Retrieving: python3-pyasn1-0.4.2-150000.3.5.1.noarch.rpm [...done (1.1 MiB/s)]
Retrieving: python3-ply-3.10-150000.3.5.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (43/83), 100.5 KiB    
Retrieving: python3-ply-3.10-150000.3.5.1.noarch.rpm [...done (546.2 KiB/s)]
Retrieving: python3-ordered-set-4.0.2-150400.8.34.noarch (Update repository with updates from SUSE Linux Enterprise 15) (44/83),  20.8 KiB    
Retrieving: python3-ordered-set-4.0.2-150400.8.34.noarch.rpm [..done]
Retrieving: python3-looseversion-1.0.2-150100.3.3.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (45/83),  16.2 KiB    
Retrieving: python3-looseversion-1.0.2-150100.3.3.1.noarch.rpm [..done]
Retrieving: python3-iniconfig-1.1.1-150000.1.11.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (46/83),  16.1 KiB    
Retrieving: python3-iniconfig-1.1.1-150000.1.11.1.noarch.rpm [..done]
Retrieving: python3-idna-2.6-150000.3.3.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (47/83),  90.0 KiB    
Retrieving: python3-idna-2.6-150000.3.3.1.noarch.rpm [...done (14.1 KiB/s)]
Retrieving: python3-chardet-3.0.4-150000.5.3.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (48/83), 171.5 KiB    
Retrieving: python3-chardet-3.0.4-150000.5.3.1.noarch.rpm [...done (1.0 MiB/s)]
Retrieving: python3-PyYAML-5.4.1-150300.3.3.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (49/83), 188.2 KiB    
Retrieving: python3-PyYAML-5.4.1-150300.3.3.1.x86_64.rpm [...done (144.1 KiB/s)]
Retrieving: python3-M2Crypto-0.38.0-150400.10.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (50/83), 276.7 KiB    
Retrieving: python3-M2Crypto-0.38.0-150400.10.1.x86_64.rpm [...done (969.1 KiB/s)]
Retrieving: python3-psutil-5.9.1-150300.3.6.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (51/83), 281.0 KiB    
Retrieving: python3-psutil-5.9.1-150300.3.6.1.x86_64.rpm [...done (1.5 MiB/s)]
Retrieving: python3-jmespath-0.9.3-150000.3.5.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (52/83),  48.3 KiB    
Retrieving: python3-jmespath-0.9.3-150000.3.5.1.noarch.rpm [...done (16.2 KiB/s)]
Retrieving: libzmq5-4.2.3-3.15.4.x86_64 (Main Repository) (53/83), 211.5 KiB    
Retrieving: libzmq5-4.2.3-3.15.4.x86_64.rpm [...done (1.4 MiB/s)]
Retrieving: systemd-presets-branding-MicroOS-20200323-lp155.2.6.noarch (Main Repository) (54/83),  12.9 KiB    
Retrieving: systemd-presets-branding-MicroOS-20200323-lp155.2.6.noarch.rpm [..done (10.6 KiB/s)]
Retrieving: python3-six-1.14.0-12.1.noarch (Main Repository) (55/83),  34.9 KiB    
Retrieving: python3-six-1.14.0-12.1.noarch.rpm [..done]
Retrieving: python3-pytz-2022.1-150300.3.6.1.noarch (Main Repository) (56/83),  56.8 KiB    
Retrieving: python3-pytz-2022.1-150300.3.6.1.noarch.rpm [...done (14.1 KiB/s)]
Retrieving: python3-pyparsing-2.4.7-1.24.noarch (Main Repository) (57/83), 187.4 KiB    
Retrieving: python3-pyparsing-2.4.7-1.24.noarch.rpm [...done (697.9 KiB/s)]
Retrieving: python3-pycparser-2.17-3.2.1.noarch (Main Repository) (58/83), 189.9 KiB    
Retrieving: python3-pycparser-2.17-3.2.1.noarch.rpm [...done (676.2 KiB/s)]
Retrieving: python3-msgpack-0.5.6-150100.3.3.1.x86_64 (Main Repository) (59/83),  88.9 KiB    
Retrieving: python3-msgpack-0.5.6-150100.3.3.1.x86_64.rpm [...done (13.5 KiB/s)]
Retrieving: python3-immutables-0.11-150000.1.3.1.x86_64 (Main Repository) (60/83),  40.2 KiB    
Retrieving: python3-immutables-0.11-150000.1.3.1.x86_64.rpm [...done (31.0 KiB/s)]
Retrieving: python3-distro-1.5.0-3.5.1.noarch (Main Repository) (61/83),  36.1 KiB    
Retrieving: python3-distro-1.5.0-3.5.1.noarch.rpm [..done]
Retrieving: python3-certifi-2018.1.18-150000.3.3.1.noarch (Main Repository) (62/83),  15.6 KiB    
Retrieving: python3-certifi-2018.1.18-150000.3.3.1.noarch.rpm [..done]
Retrieving: python3-asn1crypto-0.24.0-3.2.1.noarch (Main Repository) (63/83), 176.2 KiB    
Retrieving: python3-asn1crypto-0.24.0-3.2.1.noarch.rpm [...done (405.1 KiB/s)]
Retrieving: python3-appdirs-1.4.3-1.21.noarch (Main Repository) (64/83),  22.5 KiB    
Retrieving: python3-appdirs-1.4.3-1.21.noarch.rpm [..done]
Retrieving: python3-apipkg-2.1.0-150500.1.1.noarch (Main Repository) (65/83),  22.7 KiB    
Retrieving: python3-apipkg-2.1.0-150500.1.1.noarch.rpm [..done]
Retrieving: python3-MarkupSafe-1.0-1.29.x86_64 (Main Repository) (66/83),  29.1 KiB    
Retrieving: python3-MarkupSafe-1.0-1.29.x86_64.rpm [..done]
Retrieving: python3-Babel-2.8.0-3.3.1.noarch (Main Repository) (67/83),   5.0 MiB    
Retrieving: python3-Babel-2.8.0-3.3.1.noarch.rpm [......done (9.4 MiB/s)]
Retrieving: python3-packaging-20.3-1.9.noarch (Main Repository) (68/83),  67.5 KiB    
Retrieving: python3-packaging-20.3-1.9.noarch.rpm [...done (15.5 KiB/s)]
Retrieving: python3-cffi-1.13.2-3.2.5.x86_64 (Main Repository) (69/83), 307.1 KiB    
Retrieving: python3-cffi-1.13.2-3.2.5.x86_64.rpm [..done (2.8 KiB/s)]
Retrieving: python3-contextvars-2.4-150000.1.3.1.noarch (Main Repository) (70/83),  18.0 KiB    
Retrieving: python3-contextvars-2.4-150000.1.3.1.noarch.rpm [...done (5.0 KiB/s)]
Retrieving: python3-py-1.10.0-150100.5.12.1.noarch (Main Repository) (71/83), 138.3 KiB    
Retrieving: python3-py-1.10.0-150100.5.12.1.noarch.rpm [...done (1.6 MiB/s)]
Retrieving: systemd-249.17-150400.8.43.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (72/83),   3.4 MiB    
Retrieving: systemd-249.17-150400.8.43.1.x86_64.rpm [.....done (6.6 MiB/s)]
Retrieving: python3-Jinja2-2.10.1-150000.3.13.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (73/83), 238.0 KiB    
Retrieving: python3-Jinja2-2.10.1-150000.3.13.1.noarch.rpm [....done (1.3 MiB/s)]
Retrieving: python3-setuptools-44.1.1-150400.9.9.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (74/83), 629.1 KiB    
Retrieving: python3-setuptools-44.1.1-150400.9.9.1.noarch.rpm [...done (6.7 MiB/s)]
Retrieving: python3-pyzmq-17.1.2-150000.3.5.2.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (75/83), 464.6 KiB    
Retrieving: python3-pyzmq-17.1.2-150000.3.5.2.x86_64.rpm [...done (586.4 KiB/s)]
Retrieving: logrotate-3.18.1-150400.3.10.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (76/83),  82.4 KiB    
Retrieving: logrotate-3.18.1-150400.3.10.1.x86_64.rpm [...done]
Retrieving: python3-cryptography-3.3.2-150400.23.1.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (77/83), 437.8 KiB    
Retrieving: python3-cryptography-3.3.2-150400.23.1.x86_64.rpm [....done (1.3 MiB/s)]
Retrieving: python3-pyOpenSSL-21.0.0-150400.7.62.noarch (Update repository with updates from SUSE Linux Enterprise 15) (78/83), 111.2 KiB    
Retrieving: python3-pyOpenSSL-21.0.0-150400.7.62.noarch.rpm [...done (198.2 KiB/s)]
Retrieving: python3-urllib3-1.25.10-150300.4.12.1.noarch (Update repository with updates from SUSE Linux Enterprise 15) (79/83), 199.1 KiB    
Retrieving: python3-urllib3-1.25.10-150300.4.12.1.noarch.rpm [...done (430.7 KiB/s)]
Retrieving: python3-requests-2.25.1-150300.3.12.2.noarch (Update repository with updates from SUSE Linux Enterprise 15) (80/83), 145.0 KiB    
Retrieving: python3-requests-2.25.1-150300.3.12.2.noarch.rpm [...done (1.3 MiB/s)]
Retrieving: python3-salt-3006.0-150500.4.44.2.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (81/83),   8.7 MiB    
Retrieving: python3-salt-3006.0-150500.4.44.2.x86_64.rpm [......done (20.7 MiB/s)]
Retrieving: salt-3006.0-150500.4.44.2.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (82/83), 216.9 KiB    
Retrieving: salt-3006.0-150500.4.44.2.x86_64.rpm [..done (2.6 KiB/s)]
Retrieving: salt-minion-3006.0-150500.4.44.2.x86_64 (Update repository with updates from SUSE Linux Enterprise 15) (83/83), 215.6 KiB    
Retrieving: salt-minion-3006.0-150500.4.44.2.x86_64.rpm [...done]

Checking for file conflicts: [.......done]
( 1/83) Installing: busybox-1.35.0-150500.8.2.x86_64 [..done]
( 2/83) Installing: file-5.32-7.14.1.x86_64 [..done]
( 3/83) Installing: libargon2-1-0.0+git20171227.670229c-2.14.x86_64 [..done]
( 4/83) Installing: libip4tc2-1.8.7-1.1.x86_64 [..done]
( 5/83) Installing: libjson-c3-0.13-3.3.1.x86_64 [..done]
( 6/83) Installing: libkmod2-29-4.15.1.x86_64 [..done]
( 7/83) Installing: liblz4-1-1.9.3-150400.1.7.x86_64 [..done]
( 8/83) Installing: libmnl0-1.0.4-1.25.x86_64 [..done]
( 9/83) Installing: libpgm-5_2-0-5.2.122-150400.15.6.x86_64 [..done]
(10/83) Installing: libseccomp2-2.5.3-150400.2.4.x86_64 [..done]
(11/83) Installing: libunwind-1.5.0-4.5.1.x86_64 [..done]
(12/83) Installing: libxtables12-1.8.7-1.1.x86_64 [..done]
(13/83) Installing: pkg-config-0.29.2-1.436.x86_64 [..done]
(14/83) Installing: iproute2-5.14-150400.1.8.x86_64 [......done]
(15/83) Installing: iputils-20221126-150500.3.8.2.x86_64 [..
/usr/bin/clockdiff: cannot verify root:root 0755 - not listed in /etc/permissions
done]
(16/83) Installing: kbd-legacy-2.4.0-150400.5.6.1.noarch [...done]
(17/83) Installing: libapparmor1-3.0.4-150500.11.9.1.x86_64 [..done]
(18/83) Installing: libdevmapper1_03-2.03.22_1.02.196-150500.7.12.2.x86_64 [..done]
(19/83) Installing: libexpat1-2.4.4-150400.3.25.1.x86_64 [..done]
(20/83) Installing: libsodium23-1.0.18-150000.4.8.1.x86_64 [..done]
(21/83) Installing: libyaml-0-2-0.1.7-150000.3.2.1.x86_64 [..done]
(22/83) Installing: pam-config-1.1-150200.3.9.1.x86_64 [..
*** write_config (account, /etc/pam.d/common-account-pc, ...)
**** write config for pam_access.so (account, disabled)
**** write config for pam_unix2.so (account, disabled)
**** write config for pam_unix.so (account, enabled)
**** write config for pam_krb5.so (account, disabled)
**** write config for pam_localuser.so (account, disabled)
**** write config for pam_sss.so (account, disabled)
**** write config for pam_ldap.so (account, disabled)
**** write config for pam_nam.so (account, disabled)
**** write config for pam_winbind.so (account, disabled)
**** write config for pam_time.so (account, disabled)
*** write_config (auth, /etc/pam.d/common-auth-pc, ...)
**** write config for pam_env.so (auth, enabled)
**** write config for pam_group.so (auth, disabled)
**** write config for pam_pkcs11.so (auth, disabled)
**** write config for pam_fp.so (auth, disabled)
**** write config for pam_fprint.so (auth, disabled)
**** write config for pam_fprintd.so (auth, disabled)
**** write config for pam_thinkfinger.so (auth, disabled)
**** write config for pam_gnome_keyring.so (auth, disabled)
**** write config for pam_kwallet5.so (auth, disabled)
**** write config for pam_ssh.so (auth, disabled)
**** write config for pam_unix2.so (auth, disabled)
**** write config for pam_unix.so (auth, enabled)
**** write config for pam_ecryptfs.so (auth, disabled)
**** write config for pam_krb5.so (auth, disabled)
**** write config for pam_sss.so (auth, disabled)
**** write config for pam_ldap.so (auth, disabled)
**** write config for pam_nam.so (auth, disabled)
**** write config for pam_winbind.so (auth, disabled)
*** write_config (password, /etc/pam.d/common-password-pc, ...)
**** write config for pam_winbind.so (password, disabled)
**** write config for pam_pwcheck.so (password, disabled)
**** write config for pam_passwdqc.so (password, disabled)
**** write config for pam_cracklib.so (password, enabled)
**** write config for pam_pwhistory.so (password, disabled)
**** write config for pam_gnome_keyring.so (password, disabled)
**** write config for pam_kwallet5.so (password, disabled)
**** write config for pam_ecryptfs.so (password, disabled)
**** write config for pam_unix2.so (password, disabled)
**** write config for pam_unix.so (password, enabled)
**** write config for pam_make.so (password, disabled)
**** write config for pam_exec.so (password, disabled)
**** write config for pam_krb5.so (password, disabled)
**** write config for pam_sss.so (password, disabled)
**** write config for pam_ldap.so (password, disabled)
**** write config for pam_nam.so (password, disabled)
*** write_config (session, /etc/pam.d/common-session-pc, ...)
**** write config for pam_selinux.so (session, disabled)
**** write config for pam_mkhomedir.so (session, disabled)
**** write config for pam_systemd.so (session, disabled)
**** write config for pam_limits.so (session, enabled)
**** write config for pam_unix2.so (session, disabled)
**** write config for pam_unix.so (session, enabled)
**** write config for pam_apparmor.so (session, disabled)
**** write config for pam_krb5.so (session, disabled)
**** write config for pam_sss.so (session, disabled)
**** write config for pam_ldap.so (session, disabled)
**** write config for pam_winbind.so (session, disabled)
**** write config for pam_nam.so (session, disabled)
**** write config for pam_umask.so (session, enabled)
**** write config for pam_ssh.so (session, disabled)
**** write config for pam_selinux.so (session, disabled)
**** write config for pam_gnome_keyring.so (session, disabled)
**** write config for pam_kwallet5.so (session, disabled)
**** write config for pam_exec.so (session, disabled)
**** write config for pam_ecryptfs.so (session, disabled)
**** write config for pam_env.so (session, enabled)
**** write config for pam_mktemp.so (session, disabled)
done]
(23/83) Installing: sudo-1.9.12p1-150500.7.10.1.x86_64 [.....done]
(24/83) Installing: systemd-default-settings-branding-SLE-0.10-150300.3.7.1.noarch [..done]
(25/83) Installing: systemd-default-settings-0.10-150300.3.7.1.noarch [..done]
(26/83) Installing: systemd-presets-common-SUSE-15-150500.20.6.1.noarch [..done]
(27/83) Installing: busybox-xz-1.35.0-150400.4.5.1.noarch [..done]
(28/83) Installing: libsystemd0-249.17-150400.8.43.1.x86_64 [..done]
(29/83) Installing: kbd-2.4.0-150400.5.6.1.x86_64 [.......
Updating /etc/sysconfig/console ...
Updating /etc/sysconfig/keyboard ...
done]
(30/83) Installing: libcryptsetup12-2.4.3-150400.3.3.1.x86_64 [..done]
(31/83) Installing: libcryptsetup12-hmac-2.4.3-150400.3.3.1.x86_64 [..done]
(32/83) Installing: python3-base-3.6.15-150300.10.75.1.x86_64 [.........................done]
(33/83) Installing: libpython3_6m1_0-3.6.15-150300.10.75.1.x86_64 [...done]
(34/83) Installing: libprocps8-3.3.17-150000.7.39.1.x86_64 [..done]
(35/83) Installing: libdbus-1-3-1.12.2-150400.18.8.1.x86_64 [..done]
(36/83) Installing: python3-3.6.15-150300.10.75.1.x86_64 [..done]
(37/83) Installing: procps-3.3.17-150000.7.39.1.x86_64 [..done]
(38/83) Installing: dbus-1-1.12.2-150400.18.8.1.x86_64 [...
update-alternatives: using /usr/bin/dbus-launch.nox11 to provide /usr/bin/dbus-launch (dbus-launch) in auto mode
done]
(39/83) Installing: python3-zypp-plugin-0.6.4-150500.16.2.2.noarch [..done]
(40/83) Installing: python3-simplejson-3.17.2-150300.3.4.1.x86_64 [..done]
(41/83) Installing: python3-rpm-4.14.3-150400.59.16.1.x86_64 [..done]
(42/83) Installing: python3-pyasn1-0.4.2-150000.3.5.1.noarch [..done]
(43/83) Installing: python3-ply-3.10-150000.3.5.1.noarch [..done]
(44/83) Installing: python3-ordered-set-4.0.2-150400.8.34.noarch [..done]
(45/83) Installing: python3-looseversion-1.0.2-150100.3.3.1.noarch [..done]
(46/83) Installing: python3-iniconfig-1.1.1-150000.1.11.1.noarch [..done]
(47/83) Installing: python3-idna-2.6-150000.3.3.1.noarch [..done]
(48/83) Installing: python3-chardet-3.0.4-150000.5.3.1.noarch [..
update-alternatives: using /usr/bin/chardetect-3.6 to provide /usr/bin/chardetect (chardetect) in auto mode
done]
(49/83) Installing: python3-PyYAML-5.4.1-150300.3.3.1.x86_64 [..done]
(50/83) Installing: python3-M2Crypto-0.38.0-150400.10.1.x86_64 [..done]
(51/83) Installing: python3-psutil-5.9.1-150300.3.6.1.x86_64 [..done]
(52/83) Installing: python3-jmespath-0.9.3-150000.3.5.1.noarch [..
update-alternatives: using /usr/bin/jp-3.6 to provide /usr/bin/jp (jp) in auto mode
done]
(53/83) Installing: libzmq5-4.2.3-3.15.4.x86_64 [..done]
(54/83) Installing: systemd-presets-branding-MicroOS-20200323-lp155.2.6.noarch [..done]
(55/83) Installing: python3-six-1.14.0-12.1.noarch [..done]
(56/83) Installing: python3-pytz-2022.1-150300.3.6.1.noarch [..done]
(57/83) Installing: python3-pyparsing-2.4.7-1.24.noarch [..done]
(58/83) Installing: python3-pycparser-2.17-3.2.1.noarch [..done]
(59/83) Installing: python3-msgpack-0.5.6-150100.3.3.1.x86_64 [..done]
(60/83) Installing: python3-immutables-0.11-150000.1.3.1.x86_64 [..done]
(61/83) Installing: python3-distro-1.5.0-3.5.1.noarch [..
update-alternatives: using /usr/bin/distro-3.6 to provide /usr/bin/distro (distro) in auto mode
done]
(62/83) Installing: python3-certifi-2018.1.18-150000.3.3.1.noarch [..done]
(63/83) Installing: python3-asn1crypto-0.24.0-3.2.1.noarch [..done]
(64/83) Installing: python3-appdirs-1.4.3-1.21.noarch [..done]
(65/83) Installing: python3-apipkg-2.1.0-150500.1.1.noarch [..done]
(66/83) Installing: python3-MarkupSafe-1.0-1.29.x86_64 [..done]
(67/83) Installing: python3-Babel-2.8.0-3.3.1.noarch [..............
update-alternatives: using /usr/bin/pybabel-3.6 to provide /usr/bin/pybabel (pybabel) in auto mode
done]
(68/83) Installing: python3-packaging-20.3-1.9.noarch [..done]
(69/83) Installing: python3-cffi-1.13.2-3.2.5.x86_64 [..done]
(70/83) Installing: python3-contextvars-2.4-150000.1.3.1.noarch [..done]
(71/83) Installing: python3-py-1.10.0-150100.5.12.1.noarch [...done]
(72/83) Installing: systemd-249.17-150400.8.43.1.x86_64 [.........
Creating group systemd-journal with gid 485.
Creating group systemd-network with gid 484.
Creating user systemd-network (systemd Network Management) with uid 484 and gid 484.
Creating group systemd-timesync with gid 483.
Creating user systemd-timesync (systemd Time Synchronization) with uid 483 and gid 483.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
/usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
done]
(73/83) Installing: python3-Jinja2-2.10.1-150000.3.13.1.noarch [..done]
(74/83) Installing: python3-setuptools-44.1.1-150400.9.9.1.noarch [...done]
(75/83) Installing: python3-pyzmq-17.1.2-150000.3.5.2.x86_64 [...done]
(76/83) Installing: logrotate-3.18.1-150400.3.10.1.x86_64 [..
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Created symlink /etc/systemd/system/timers.target.wants/logrotate.timer -> /usr/lib/systemd/system/logrotate.timer.
done]
(77/83) Installing: python3-cryptography-3.3.2-150400.23.1.x86_64 [...done]
(78/83) Installing: python3-pyOpenSSL-21.0.0-150400.7.62.noarch [..done]
(79/83) Installing: python3-urllib3-1.25.10-150300.4.12.1.noarch [..done]
(80/83) Installing: python3-requests-2.25.1-150300.3.12.2.noarch [..done]
(81/83) Installing: python3-salt-3006.0-150500.4.44.2.x86_64 [............................done]
(82/83) Installing: salt-3006.0-150500.4.44.2.x86_64 [...done]
(83/83) Installing: salt-minion-3006.0-150500.4.44.2.x86_64 [..
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
done]
Running post-transaction scripts [..
%posttrans(systemd-presets-common-SUSE-15-150500.20.6.1.noarch) script output:
Created symlink /etc/systemd/system/default.target.wants/ca-certificates.path -> /usr/lib/systemd/system/ca-certificates.path.
Created symlink /etc/systemd/system/getty.target.wants/getty@tty1.service -> /usr/lib/systemd/system/getty@.service.
Created symlink /etc/systemd/system/multi-user.target.wants/kbdsettings.service -> /usr/lib/systemd/system/kbdsettings.service.
Created symlink /etc/systemd/system/multi-user.target.wants/remote-fs.target -> /usr/lib/systemd/system/remote-fs.target.
Created symlink /etc/systemd/user/timers.target.wants/systemd-tmpfiles-clean.timer -> /usr/lib/systemd/user/systemd-tmpfiles-clean.timer.
Created symlink /etc/systemd/user/basic.target.wants/systemd-tmpfiles-setup.service -> /usr/lib/systemd/user/systemd-tmpfiles-setup.service.
...done]
 *  INFO: Running install_opensuse_onedir_post()
Created symlink /etc/systemd/system/multi-user.target.wants/salt-minion.service → /usr/lib/systemd/system/salt-minion.service.
 *  INFO: Running install_opensuse_check_services()
 * ERROR: Failed to run install_opensuse_check_services()!!!
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
 * DEBUG: Removing the temporary apt error file /tmp/apt_error.N6fNkb
sh-4.4# salt-minion --version
salt-minion 3006.0 (Sulfur)
sh-4.4# sh bootstrap-salt.sh -v
bootstrap-salt.sh -- Version 2024.11.29

```

**Comment by dmurphy18** [comment]
@jeff350 Amazed to see ``` open-vm-tools-salt-minion``` since also responsible for that, and really only there to install a salt-minion with VMware's VM Tools, but the script can be used independently, just a bash script.  That script ```svtminion.sh``` is currently being updated to work on the new infrastructure, and will only support 3006.0 and up.  However, the preferred method to install is using bootstrap-salt.sh since it allows installing salt-master, salt-api, etc.

Have changes already underway for supporting Salt on Suse, and made the decision to go with the saltproject packages only, given that the SUSE provided packages are very old, and there have been CVE updates to the salt-minion since 3006.0/3006.1 have been released.  Current PR is https://github.com/saltstack/salt-bootstrap/pull/2066, but given no SUSE containers in the new Salt pipelines, will be doing the testing by hand.

Testing against current SUSE SLES 15sp6, and opensuse leap 15.6 (16.0 could not find iso to install), current opensuse tumbleweed was too unstable in VM.

**Comment by dmurphy18** [comment]
@jeff350 Running into issues getting containers with systemd to work (docker and podman), and can only use VirtualBox VMs at home (locked down network in the office). If you could run through the added support for using Salt Project packages in PR https://github.com/saltstack/salt-bootstrap/pull/2066, that would be helpful.  Will try at home over the weekend too.

Note: the bootstrap-script tests for systemd support and fails if not available, since rely on systemd to stop/start/status of salt-minion etc. The old classic packaging support for /etc/init.d is missing with the onedir architecture, an item for discussion within the team, but have to deal with what is already released.

Note: the containers used as part of the new CI/CD on GitHub pipeline have systemd support, but SUSE are not part of those containers, since SUSE did their own packaging.  Something to be discussed in the future but unlikely to be resolved till after the Christmas break at this point.

**Comment by dmurphy18** [comment]
@jeff350 So found a way to bring up the VM's at work and opensuse leap 15.6 work fine, except for one problem, it look like SUSE is old and doesn't allow for 'exclude' statements in repo files, so getting 3007.1 regardless. Had similar issue on Photon, so will port those changes to also apply with SUSE.

SLES 15 VM is having issues with dependencies, need to add some functions for 'sled', C & P from opensuse should fix that.

**Comment by jeff350** [comment]
@dmurphy18 I was able to verify that it installed the salt-minion correctly on:
- Opensuse Leap 15.5 container
- Opensuse Leap 15.6  container
- Opensuse Tumbleweed container
- Opensuse Tumbleweed VM Server install
- Opensuse Leap 15.6 VM Server install

I did this with the commands:

1. curl -o bootstrap-salt.sh -L https://raw.githubusercontent.com/dmurphy18/salt-bootstrap/refs/heads/upd_suse_support/bootstrap-salt.sh
2. sh bootstrap-salt.sh -D stable


I don't know how this was done with Photon but locking with zypper is always an option. 
3006: `zypper addlock "salt-minion < 3006" && zypper addlock "salt-minion >= 3007"`
3007: `zypper addlock "salt-minion < 3007" && zypper addlock "salt-minion >= 3008"`

I looked at this when I was creating instructions for the salt install guide https://github.com/saltstack/salt-install-guide/pull/14

**Comment by dmurphy18** [comment]
@jeff350 Thanks for that, fixed SUSE 15 and hand testing that right now, was trying what worked for Photon, but will update with ```addlick```. Had seen that earlier from your previous.

**Comment by dmurphy18** [comment]
@jeff350 Please check the current bootstrap-salt.sh associated with https://github.com/saltstack/salt-bootstrap/pull/2066 for packaging install.  Fixing an issue with git master install on SLES 15, git not installed by default.

Make use of addlock (thanks), once you pass them , will release a new bootstrap script

**Comment by jeff350** [comment]
I am seeing that the versioned installs now works and I am able to install `onedir 3006` to get 3006.9 installed with appropriate locks in place. 

I would also recommend ensuring `awk` is installed as this will also allow it to support opensuse tumbleweed.  

I am still seeing an issue installing with git but this looks like it is related to using an older python  (3.6) on SLES 15.5 and 15.6. That may need to specify a newer python package to be used for git installs. This should be able to be solved by defaulting PV to 3.11 for SUSE Git installs and ensuring the packages `python311 python311-pip python311-devel` are installed.

>
> * DEBUG: Installing Salt requirements from PyPi, pip3.6 install  --ignore-installed --prefix=/usr -r requirements/static/ci/py3.6/linux.txt
> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements/static/ci/py3.6/linux.txt'
> Failed to install salt requirements for the version of Python 3.6
>  * ERROR: Failed to run install_opensuse_15_git()!!!

But this looks good to me for doing 3006 and 3007 installs on SUSE leap 15.5 and 15.6.

**Comment by dmurphy18** [comment]
Will release, without adding gawk, since SLES 15 has issues if try including it, also number of issues with various dependencies with, for example
```
tsuse15:/home/david # zypper -n install python3-PyYAML python3-requests python3-zypp gawk
Loading repository data...
Reading installed packages...
Package 'python3-PyYAML' not found.
Package 'python3-zypp' not found.
'gawk' is already installed.
Package 'gawk' is not available in your repositories. Cannot reinstall, upgrade, or downgrade.
'python3-requests' is already installed.
Package 'python3-requests' is not available in your repositories. Cannot reinstall, upgrade, or downgrade.
tsuse15:/home/david # 
```
So some dependencies resolution for SLES 15 to be done, and as for git, tried various, git-core, git etc. even though I can see them in zypper repositories.  But as you said, Python 3.6, so long EOL, must say I am sad to see SUSE not keeping up to date.

**Comment by dmurphy18** [comment]
@jeff350 Released v2024.12.09 , see https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh
