### ISSUE TITLE
minion Bootstrap fails on RHEL Workstation 6.5

### ISSUE THREAD

**Issue by ghost** [saltstack/salt-bootstrap#304]
```
# wget -O - http://bootstrap.saltstack.org | sh
--2014-02-12 12:41:36--  http://bootstrap.saltstack.org/
Resolving bootstrap.saltstack.org... 74.208.29.198
Connecting to bootstrap.saltstack.org|74.208.29.198|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
--2014-02-12 12:41:36--  https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Resolving raw.github.com... 199.27.79.133
Connecting to raw.github.com|199.27.79.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 122465 (120K) [text/plain]
Saving to: “STDOUT”

 0% [                                                                                                   ] 0           --.-K/s               *  INFO: PIPED THROUGH sh -- Version 1.5.11

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   2.6.32-431.5.1.el6.x86_64
 *  INFO:   Distribution: Red Hat Enterprise Workstation 6.5

 *  INFO: Installing minion
100%[==================================================================================================>] 122,465      545K/s   in 0.2s

2014-02-12 12:41:36 (545 KB/s) - written to stdout [122465/122465]

 *  INFO: Found function daemons_running
 * ERROR: No dependencies installation function found. Exiting...
```

I've seen the same "No dependencies" error in a few other Issues that have since been closed (#22, #55 ) but thought it worth creating an issue because those were closed for other distros.

Installing EPEL and then running yum install salt-minion also fails, but with the same python-jinja2 error as is noted in Issue #302 

```
# yum install salt-minion
Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
This system is receiving updates from Red Hat Subscription Management.
rhel-6-workstation-rhev-agent-rpms                                                                                   | 3.1 kB     00:00
rhel-6-workstation-rpms                                                                                              | 3.8 kB     00:00
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package salt-minion.noarch 0:0.17.4-1.el6 will be installed
--> Processing Dependency: salt = 0.17.4-1.el6 for package: salt-minion-0.17.4-1.el6.noarch
--> Running transaction check
---> Package salt.noarch 0:0.17.4-1.el6 will be installed
--> Processing Dependency: sshpass for package: salt-0.17.4-1.el6.noarch
--> Processing Dependency: python-zmq for package: salt-0.17.4-1.el6.noarch
--> Processing Dependency: python-msgpack for package: salt-0.17.4-1.el6.noarch
--> Processing Dependency: python-jinja2 for package: salt-0.17.4-1.el6.noarch
--> Processing Dependency: PyYAML for package: salt-0.17.4-1.el6.noarch
--> Running transaction check
---> Package PyYAML.x86_64 0:3.10-3.el6 will be installed
--> Processing Dependency: libyaml-0.so.2()(64bit) for package: PyYAML-3.10-3.el6.x86_64
---> Package python-msgpack.x86_64 0:0.1.13-3.el6 will be installed
---> Package python-zmq.x86_64 0:2.2.0.1-1.el6 will be installed
--> Processing Dependency: libzmq.so.3()(64bit) for package: python-zmq-2.2.0.1-1.el6.x86_64
---> Package salt.noarch 0:0.17.4-1.el6 will be installed
--> Processing Dependency: python-jinja2 for package: salt-0.17.4-1.el6.noarch
---> Package sshpass.x86_64 0:1.05-1.el6 will be installed
--> Running transaction check
---> Package libyaml.x86_64 0:0.1.3-1.el6 will be installed
---> Package salt.noarch 0:0.17.4-1.el6 will be installed
--> Processing Dependency: python-jinja2 for package: salt-0.17.4-1.el6.noarch
---> Package zeromq3.x86_64 0:3.2.4-1.el6 will be installed
--> Processing Dependency: libpgm-5.1.so.0()(64bit) for package: zeromq3-3.2.4-1.el6.x86_64
--> Running transaction check
---> Package openpgm.x86_64 0:5.1.118-3.el6 will be installed
---> Package salt.noarch 0:0.17.4-1.el6 will be installed
--> Processing Dependency: python-jinja2 for package: salt-0.17.4-1.el6.noarch
--> Finished Dependency Resolution
Error: Package: salt-0.17.4-1.el6.noarch (epel)
           Requires: python-jinja2
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by s0undt3ch** [comment]
Can you please try using:

```
wget -O - http://bootstrap.saltstack.org | sh -s -- -D
```

It will give me some additional information. Thanks.

**Comment by ghost** [comment]
Not much more info to be had, but I hope it helps:

```
# wget -O - http://bootstrap.saltstack.org | sh -s -- -D
--2014-02-12 15:53:44--  http://bootstrap.saltstack.org/
Resolving bootstrap.saltstack.org... 74.208.29.198
Connecting to bootstrap.saltstack.org|74.208.29.198|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
--2014-02-12 15:53:44--  https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Resolving raw.github.com... 199.27.79.133
Connecting to raw.github.com|199.27.79.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 122465 (120K) [text/plain]
Saving to: “STDOUT”

 0% [                                                                                                   ] 0           --.-K/s               *  INFO: PIPED THROUGH sh -- Version 1.5.11

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   2.6.32-431.5.1.el6.x86_64
 *  INFO:   Distribution: Red Hat Enterprise Workstation 6.5

 *  INFO: Installing minion
100%[==================================================================================================>] 122,465      552K/s   in 0.2s

2014-02-12 15:53:45 (552 KB/s) - written to stdout [122465/122465]

 * DEBUG: install_red_hat_enterprise_workstation_6_stable_deps not found....
 * DEBUG: install_red_hat_enterprise_workstation_6_5_stable_deps not found....
 * DEBUG: install_red_hat_enterprise_workstation_6_deps not found....
 * DEBUG: install_red_hat_enterprise_workstation_6_5_deps not found....
 * DEBUG: install_red_hat_enterprise_workstation_stable_deps not found....
 * DEBUG: install_red_hat_enterprise_workstation_deps not found....
 * DEBUG: DEPS_INSTALL_FUNC=null
 * DEBUG: CONFIG_SALT_FUNC=null
 * DEBUG: PRESEED_MASTER_FUNC=null
 * DEBUG: install_red_hat_enterprise_workstation_6_stable not found....
 * DEBUG: install_red_hat_enterprise_workstation_6_5_stable not found....
 * DEBUG: install_red_hat_enterprise_workstation_stable not found....
 * DEBUG: INSTALL_FUNC=null
 * DEBUG: install_red_hat_enterprise_workstation_6_stable_post not found....
 * DEBUG: install_red_hat_enterprise_workstation_6_5_stable_post not found....
 * DEBUG: install_red_hat_enterprise_workstation_6_post not found....
 * DEBUG: install_red_hat_enterprise_workstation_6_5_post not found....
 * DEBUG: install_red_hat_enterprise_workstation_stable_post not found....
 * DEBUG: install_red_hat_enterprise_workstation_post not found....
 * DEBUG: POST_INSTALL_FUNC=null
 * DEBUG: install_red_hat_enterprise_workstation_6_stable_restart_daemons not found....
 * DEBUG: install_red_hat_enterprise_workstation_6_5_stable_restart_daemons not found....
 * DEBUG: install_red_hat_enterprise_workstation_6_restart_daemons not found....
 * DEBUG: install_red_hat_enterprise_workstation_6_5_restart_daemons not found....
 * DEBUG: install_red_hat_enterprise_workstation_stable_restart_daemons not found....
 * DEBUG: install_red_hat_enterprise_workstation_restart_daemons not found....
 * DEBUG: STARTDAEMONS_INSTALL_FUNC=null
 * DEBUG: daemons_running_red_hat_enterprise_workstation_6_stable not found....
 * DEBUG: daemons_running_red_hat_enterprise_workstation_6_5_stable not found....
 * DEBUG: daemons_running_red_hat_enterprise_workstation_6 not found....
 * DEBUG: daemons_running_red_hat_enterprise_workstation_6_5 not found....
 * DEBUG: daemons_running_red_hat_enterprise_workstation_stable not found....
 * DEBUG: daemons_running_red_hat_enterprise_workstation not found....
 *  INFO: Found function daemons_running
 * DEBUG: DAEMONS_RUNNING_FUNC=daemons_running
 * ERROR: No dependencies installation function found. Exiting...
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
```

**Comment by gravyboat** [comment]
@alexthegraham Same questions as https://github.com/saltstack/salt-bootstrap/issues/302, is the RHEL optional repo installed?

**Comment by s0undt3ch** [comment]
The problem here is that we don't tread "Red Hat Enterprise Workstation" as "Red Hat Enterprise", so no functions will be found

**Comment by ghost** [comment]
Enabling the optional repo allows "yum install salt-minion" to work, but doesn't correct the OP "ERROR: No dependencies installation function found." problem.

**Comment by s0undt3ch** [comment]
@alexthegraham can I ask you for a temporary ssh access to a workstation machine?

If not, does one of those have the `lsb_release` binary available?
What's the output of `lsb_release -si`?

**Comment by s0undt3ch** [comment]
No need. I've fixed what I needed to.

**Comment by joshbaptiste** [comment]
Can Scientific Linux also be added as a RedHat/Centos alternative?

```
root@localhost:/home/prchery $ wget -O - http://bootstrap.saltstack.org | sh
--2014-03-18 00:54:40--  http://bootstrap.saltstack.org/
Resolving bootstrap.saltstack.org... 74.208.29.198
Connecting to bootstrap.saltstack.org|74.208.29.198|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh [following]
--2014-03-18 00:54:40--  https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
Resolving raw.github.com... 199.27.76.133
Connecting to raw.github.com|199.27.76.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 151188 (148K) [text/plain]
Saving to: “STDOUT”

 0% [                                                                                                                               ] 0           --.-K/s               *  INFO: PIPED THROUGH sh -- Version 2014.03.10-1

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   2.6.32-042stab085.17
 *  INFO:   Distribution: Scientific 6.5

 *  INFO: Installing minion
100%[==============================================================================================================================>] 151,188      510K/s   in 0.3s    

2014-03-18 00:54:40 (510 KB/s) - written to stdout [151188/151188]

 *  INFO: Found function daemons_running
 * ERROR: No dependencies installation function found. Exiting..


root@localhost:/home/prchery $ lsb_release -ir
Distributor ID: Scientific
Release:        6.5
```

I got it to install fine by modifying these "bootstrap.sh" lines version 2014.03.10-1
    746         DISTRO_NAME=Centos
    747         DISTRO_VERSION=6.5

**Comment by s0undt3ch** [comment]
Sure! I'll get this into the script asap

**Comment by signalraket** [comment]
Is it the same issue that I have with Solaris 11?

```
# sh ./install_salt.sh -G git
 *  INFO: Running version: 2016.07.07
 *  INFO: Executed by: sh
 *  INFO: Command line: './install_salt.sh -G git'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     i86pc
 *  INFO:   OS Name:      SunOS
 *  INFO:   OS Version:   5.11
 *  INFO:   Distribution: Oracle Solaris 11

 *  INFO: Installing minion
 *  INFO: Found function daemons_running
 * ERROR: No dependencies installation function found. Exiting...
# cat /etc/release 
                             Oracle Solaris 11.3 X86
  Copyright (c) 1983, 2015, Oracle and/or its affiliates.  All rights reserved.
                            Assembled 06 October 2015
```

Also, make sure that you are running gnu sed and gnu awk. Update your $PATH before you run the script. You find them in /usr/gnu/bin, otherwise install them with;
pkg install gnu-sed
pkg install gawk

Regards,
S

**Comment by vutny** [comment]
@signalraket It's kind of...
Oracle Solaris is detected by the bootstrap script, but the actual installation functions are still not implemented. See https://github.com/saltstack/salt-bootstrap#adding-support-for-other-operating-systems
