### ISSUE TITLE
Bootstrap script requires python-jinja2 before installing Salt COPR

### ISSUE THREAD

**Issue by sjmh** [saltstack/salt-bootstrap#669]
When using the bootstrap script to install onto a RHEL6 box, the script tries to verify that python-jinja2 is available. Normally, this is in the RHEL Optionals channel, but the Salt COPR repo now has python-jinja2 in it.

Seems it would make more sense to configure the Salt COPR yum repo before attempting to check if python-jinja2 is available to cut back on the amount of configuration needed for the host to actually bootstrap salt.

I've confirmed it works by manually configuring the Salt COPR repo, then attempting the bootstrap. The python-jinja2 is detected in the repo. It then goes onto fail on python-urllib3 missing ( which isn't part of the Salt COPR, EPEL, the RHEL media or the RHEL optional channels, but is only available via the RHEL updates channel.. )

It'd also be nice to see all the RPM requirements needed for a 'bootstrap' in the Salt COPR eventually, if we're trying to get to a true 'bootstrap', rather than a 'do a bunch of other configuration, and then bootstrap'.

**Comment by rallytime** [comment]
This is related to #668, and when the bootstrap script is moved to http://repo.saltstack.com, this issue might not be as relevant anymore, as I believe we'll be handling those dependencies there. However, we definitely should make sure these issues are addressed when that happens.

Thoughts @s0undt3ch or @dmurphy18?

**Comment by jfindlay** [comment]
@sjmh, with #674, we should be able to migrate away from COPR for RHEL 5/6/7.  While this does not fix the issue directly, COPR should no longer be needed now that we're providing packages on repo.saltstack.com.

**Comment by s0undt3ch** [comment]
#674 was merged. Closing. Please re-open if necessary.

**Comment by sjmh** [comment]
@s0undt3ch and @jfindlay - not sure if this should be closed.

This is less 'Stop relying on COPR' and more 'Stop testing for the Optionals channel for an RPM that you don't need from it'.

Case in point:

New RHEL6u6 VM with barebones install (@Core, @Base) and no yum repos configured.  Bootstrap will fail, looking for python-jinja2 to see if the Optionals channel exists.

If you remove the test for python-jinja2, the bootstrap goes onto fail on python-backports-ssl_match_hostname not existing.

But, let's say you have a case where the system already has python-backports-ssl_match_hostname installed and the test still exists for python-jinja2.  It still fails on the Optionals channel, which is pointless, because if you disable that test, the bootstrap now works ( which I tested.. )

In essence, the bootstrap script is testing for an rpm in the Optional channel that it doesn't need from the Optional channel.

So my suggestion would either be that the test needs to either check for python-backports-ssl_match_hostname instead, since that's what the bootstrap actually needs from Optionals, or to just move python-backports-ssl_match_hostname and python-backports into repo.saltstack.com all together and get rid of the need for Optionals.

Thoughts?

**Comment by s0undt3ch** [comment]
I've reopened the issue to address your concerns. I say we move whatever is necessary to SaltStack's repo...

**Comment by sjmh** [comment]
That'd be my vote as well - it appears these would need to be added:

python-backports-ssl_match_hostname
python-backports
python-msgpack
python-ordereddict

msgpack and ordereddict come from EPEL, which is installed by the bootstrap script - but everything should be in repo.saltstack.com, would need to move those as well.  The backport RPMs are the only ones that are required from Optionals.

Tested on a RHEL6u6 VM with --nobase ( so only @Core ) - pretty minimal install.  I pre-installed the two backport RPMs ( then removed all my yum repos ) and commented out line https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L3348.  After that, bootstrap was able to install the minion.

**Comment by sjmh** [comment]
Ah, looks like msgpack and ordereddict are already in repo.saltstack.com - so just the backports are missing.

**Comment by vutny** [comment]
Hi @sjmh,

```
# head -n 1 /etc/issue
CentOS release 6.7 (Final)
# repoquery -a --qf "%-20{repoid} %{name} %{version}" | grep python-backports
repo-saltstack-el6   python-backports 1.0
base                 python-backports 1.0
epel                 python-backports-lzma 0.0.2
extras               python-backports-ssl_match_hostname 3.4.0.2
```

I assume that RHEL 6.7 also contains all necessary packages in its base repos.

**Comment by sjmh** [comment]
@vutny Yeah, the packages were added in the last few weeks.

With those packages in the repo now, we shouldn't need the optionals repo from RHEL anymore, but the bootstrap script is still checking for it.

**Comment by vutny** [comment]
@sjmh I did a fresh bootstrap on CentOS 6.7 minimal container.

``` sh
# repoquery -a --qf "%{repoid}" | sort | uniq 
base
epel
extras
repo-saltstack-el6
updates
# yum list installed | grep '^python.\+@base'
python-babel.noarch         0.9.4-5.1.el6                    @base              
python-backports.x86_64     1.0-5.el6                        @base              
python-chardet.noarch       2.2.1-1.el6                      @base              
python-jinja2.x86_64        2.2.1-2.el6_5                    @base              
python-requests.noarch      2.6.0-3.el6                      @base              
python-six.noarch           1.9.0-2.el6                      @base              
python-urllib3.noarch       1.10.2-1.el6                     @base
# yum list installed | grep -B1 @extras
python-backports-ssl_match_hostname.noarch
                            3.4.0.2-4.el6.centos             @extras
# yum list installed | grep @epel 
python-msgpack.x86_64       0.4.6-1.el6                      @epel              
# yum list installed | grep @repo-saltstack-el6
PyYAML.x86_64               3.11-1.el6                       @repo-saltstack-el6
python-crypto.x86_64        2.6.1-2.el6                      @repo-saltstack-el6
python-futures.noarch       3.0.3-1.el6                      @repo-saltstack-el6
python-markupsafe.x86_64    0.11-10.el6                      @repo-saltstack-el6
python-tornado.x86_64       4.2.1-1.el6                      @repo-saltstack-el6
python-zmq.x86_64           14.5.0-2.el6                     @repo-saltstack-el6
salt.noarch                 2015.8.3-1.el6                   @repo-saltstack-el6
salt-minion.noarch          2015.8.3-1.el6                   @repo-saltstack-el6
zeromq.x86_64               4.0.5-4.el6                      @repo-saltstack-el6
```

I've looked through CentOS Install Functions code in the latest 'develop' version, there are no additional repositories checked and configured except `epel` and `repo-saltstack-el6` for CentOS 6.
But for RHEL and Oracle, we have `__test_rhel_optionals_packages()` which checks for `server-releases-optional` repo, so it's little bit different, just like you said.

I also need to bootstrap some RHEL 6.X machine, so I will try to test those things and fix if necessary. 

Side question to @saltstack team:
- Bootstrap assumes `extras` repo is enabled by default on a fresh installation or image of CentOS 6. Do we need to check that? It is reqiuired to install `python-backports-ssl_match_hostname` package.

**Comment by vutny** [comment]
Nevermind, I see that `python-backports-ssl_match_hostname` is now in `repo-saltstack-el6` and it will be installed by dependency with  `python-tornado`.

**Comment by vutny** [comment]
Created PR. Verified that `rhui-*-server-releases-optional` repo is neither checked nor enabled.
Tested on RHEL 6.6: https://gist.github.com/vutny/d413aeda143742103843

**Comment by jfindlay** [comment]
@vutny, if that is where `python-backports-ssl_match_hostname` needs to come from, then it makes sense to check for it.

**Comment by vutny** [comment]
@jfindlay As I said before, `python-backports-ssl_match_hostname` is not a direct dependency for now. It will be installed when `yum` resolve the following dependency chain `salt-minion --> salt --> python-tornado --> python-backports-ssl_match_hostname`:

``` bash
# repoquery --qf "%-20{repoid} %-24{name} %{version}" --whatrequires python-backports-ssl_match_hostname
extras               python-backports-ssl_match_hostname 3.4.0.2
epel                 python-tornado           2.2.1
repo-saltstack-el6   python-tornado           4.2.1
repo-saltstack-el6   python-tornado           4.2.1
extras               python-urllib3           1.5
repo-saltstack-el6   python-urllib3           1.10.2
epel                 python-websocket-client  0.14.1
epel                 transifex-client         0.10
# repoquery --qf "%-20{repoid} %-24{name} %{version}" --whatrequires python-tornado
repo-saltstack-el6   python-tornado           4.2.1
repo-saltstack-el6   python-tornado           4.2.1
epel                 python-tornado           2.2.1
epel                 python-TornadIO2         0.0.4
epel                 python-ipython-notebook  0.13.2
epel                 python-testify           0.4.0
extras               python-tornado-doc       2.2.1
epel                 python-tornado-doc       2.2.1
repo-saltstack-el6   python-tornado-doc       4.2.1
repo-saltstack-el6   python-tornado-doc       4.2.1
repo-saltstack-el6   salt                     2015.8.3
epel                 uwsgi-plugin-tornado     2.0.11.1
# repoquery --qf "%-20{repoid} %-24{name} %{version}" --whatrequires salt
repo-saltstack-el6   salt                     2015.8.3
epel                 salt-api                 0.8.2
epel                 salt-cloud               0.8.8
epel                 salt-master              2015.5.5
repo-saltstack-el6   salt-master              2015.8.3
epel                 salt-minion              2015.5.5
repo-saltstack-el6   salt-minion              2015.8.3
epel                 salt-ssh                 2015.5.5
repo-saltstack-el6   salt-ssh                 2015.8.3
epel                 salt-syndic              2015.5.5
repo-saltstack-el6   salt-syndic              2015.8.3
```

I clearly see that package file is present in the repo:
http://repo.saltstack.com/yum/rhel6/python-backports-ssl_match_hostname-3.4.0.2-2.el6.noarch.rpm

But it is missing in the repodata. So this is a real issue that need to be fixed. Please recreate the repodata. This affects only CentOS 6, RHEL6 contains the package in its main repo: `rhui-*-rhel-server-releases`.

Thanks.

**Comment by vutny** [comment]
@jfindlay Hey, looks like `python-backports-ssl_match_hostname` was copied to `base` repo in CentOS 6 too!

``` bash
# yum --disablerepo=extras info python-backports-ssl_match_hostname
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.mirohost.net
 * epel: ftp.colocall.net
 * updates: mirror.mirohost.net
Available Packages
Name        : python-backports-ssl_match_hostname
Arch        : noarch
Version     : 3.4.0.2
Release     : 2.el6
Size        : 12 k
Repo        : base
Summary     : The ssl.match_hostname() function from Python 3
URL         : https://bitbucket.org/brandon/backports.ssl_match_hostname
License     : Python
```

So you just need to remove it from http://repo.saltstack.com/yum/rhel6/.
I think this is no longer the issue.

**Comment by jfindlay** [comment]
thanks, @vutny.  Ping @dmurphy18.

**Comment by vutny** [comment]
@dmurphy18 Could you please remove the `python-backports-ssl_match_hostname` from RHEL6 repo? It's not in the repodata right now, and the same package is already exists in standard RHEL/CentOS repos.

Thanks in advance!

**Comment by sjmh** [comment]
@vutny - why would we want to remove this?  The boot strap repos should contain all RPMs needed to install Salt - not just ones that are not in the RHEL standard repos.

**Comment by vutny** [comment]
@sjmh Obviously because we want to get updates and bug-fixes from the Red Hat or any other vendor. Also, other software on your machine could possibly depend on the newer version of the package, and you will end up locked on the Salt repo to be always in sync with latest OS patch-level.
Otherwise Salt would need to ship its own Python interpreter and a lot of system core utils :-)

**Comment by sjmh** [comment]
@vutny - except that that the RHEL @Core image already has all that.  Right now, the repo has everything you need to install Salt onto a vanilla RHEL box.  

I'd argue that Salt wants to control the dependencies.  If I'm using the RPM versions that Salt provides, rather than from my RHEL repos, which may update to versions that break things in Salt, then you end up with more issues.

It's the way vendors are going - see docker or ChefDK.  Shipping all the dependencies as batteries included provides alot less hassle to the end user.

EPEL would be one thing, but removing something that is required from RHEL's standard repo means that Salt's bootstrap isn't really a bootstrap.  It's a 'Go setup your RHN dependencies first, and THEN you can bootstrap'.

**Comment by vutny** [comment]
@sjmh Completely agree with you. This particular package we talked above is the part of RHEL `@Core` and CentOS `@base` repos now. Recently I've did a bootstrap on RHEL6 official AMI, everything works just fine and straightforward. No additional RHN subscriptions required.
See my log here: https://gist.github.com/vutny/d413aeda143742103843

**Comment by sjmh** [comment]
@vutny  python-backports-ssl_match_hostname isn't in RHEL's @Core.  See #724.  On a no-base install, RHEL still needs that package via the repo.

**Comment by vutny** [comment]
@sjmh Ah, I guess I misunderstood your point from the start. You mentioned the pre-installed group of packages while I was thinking about the actual repository where they came from.
Now it makes sense to me. 

```
$ lsb_release -d
Description:    Red Hat Enterprise Linux Server release 6.6 (Santiago)
$ sudo repoquery --qf "%{repoid} %{name} %{version}" --all | grep python-backports-ssl_match_hostname
rhui-REGION-rhel-server-releases python-backports-ssl_match_hostname 3.4.0.2
```

`rhui-REGION-rhel-server-releases` repository is a main RHEL repo for EC2.

My concern is that Salt requires some of system packages which may need to be installed/upgraded during the bootstrap:

```
$ sudo repoquery --requires salt
/bin/sh
/usr/bin/python
PyYAML
chkconfig
initscripts
pciutils
python(abi) = 2.6
python-crypto >= 2.6.1
python-futures >= 2.0
python-jinja2
python-markupsafe
python-msgpack > 0.3
python-requests >= 1.0.0
python-six
python-tornado >= 4.2.1
python-zmq
which
yum-utils
```

Personally, for clarity and determinacy reasons I don't want to get something like `yum-utils` from any other source than official (or my own) repository, even GPG signed correctly. But it's more a matter of priorities.
