### ISSUE TITLE
salt bootstrap fails on vanilla debian jessie 8

### ISSUE THREAD

**Issue by bytebae** [saltstack/salt-bootstrap#682]
Hi,

The following was performed:

```
$ wget -O install_salt.sh https://bootstrap.saltstack.com
```

```
$ sudo sh install_salt.sh -P -M git v2015.8.1
```

O/P:

```
 *  INFO: sh install_salt.sh -- Version 2015.08.06

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.16.0-4-amd64
 *  INFO:   Distribution: Debian 8.0

 *  INFO: Installing minion
 *  INFO: Installing master
 *  INFO: Found function install_debian_8_git_deps
 *  INFO: Found function install_debian_8_git
 *  INFO: Found function install_debian_git_post
 *  INFO: Found function install_debian_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_debian_check_services
 *  INFO: Running install_debian_8_git_deps()

etc, etc,...
```

ending with

```
Writing /usr/lib/python2.7/dist-packages/salt-2015.8.1.egg-info
 *  INFO: Running install_debian_git_post()
Created symlink from /etc/systemd/system/multi-user.target.wants/salt-minion.service to /etc/systemd/system/salt-minion.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/salt-master.service to /etc/systemd/system/salt-master.service.
 *  INFO: Running install_debian_check_services()
 *  INFO: Running install_debian_restart_daemons()
Job for salt-master.service failed. See 'systemctl status salt-master.service' and 'journalctl -xn' for details.
 *  INFO: Running daemons_running()
 * ERROR: salt-master was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
 * ERROR: salt-master was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...

```

Let me know what else you'd like me to share regarding this.

**Comment by bytebae** [comment]
```
$ sudo systemctl status salt-master.service
● salt-master.service - The Salt Master Server
   Loaded: loaded (/etc/systemd/system/salt-master.service; enabled)
   Active: failed (Result: timeout) since Tue 2015-11-03 13:50:48 UTC; 1h 30min ago
  Process: 1833 ExecStart=/usr/bin/salt-master (code=exited, status=0/SUCCESS)
 Main PID: 1833 (code=exited, status=0/SUCCESS)

Nov 03 13:50:48 ip-10-238-132-13 systemd[1]: salt-master.service start operation timed out. Terminating.
Nov 03 13:50:48 ip-10-238-132-13 systemd[1]: Failed to start The Salt Master Server.
Nov 03 13:50:48 ip-10-238-132-13 systemd[1]: Unit salt-master.service entered failed state.
```

**Comment by bytebae** [comment]
Apparently, commenting out the line: Type=notify, from the salt-master.service file gets the master running after a restart. 

```
[Unit]
Description=The Salt Master Server
After=syslog.target network.target

[Service]
LimitNOFILE=16384
#Type=notify
ExecStart=/usr/bin/salt-master

[Install]
WantedBy=multi-user.target

```

**Comment by jfindlay** [comment]
@hubricode, thanks for the report.  Do you have the same problems with `wget -O install_salt.sh https://bootstrap.saltstack.com/develop`?

**Comment by bytebae** [comment]
Nope. Still getting this:

```
Writing /usr/lib/python2.7/dist-packages/salt-2015.8.1.egg-info
 *  INFO: Running install_debian_git_post()
Created symlink from /etc/systemd/system/multi-user.target.wants/salt-minion.service to /etc/systemd/system/salt-minion.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/salt-master.service to /etc/systemd/system/salt-master.service.
 *  INFO: Running install_debian_check_services()
 *  INFO: Running install_debian_restart_daemons()
Job for salt-master.service failed. See 'systemctl status salt-master.service' and 'journalctl -xn' for details.
 *  INFO: Running daemons_running()
 * ERROR: salt-master was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
 * ERROR: salt-master was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
```

Commands run were:

```
$ wget -O install_salt.sh https://bootstrap.saltstack.com/develop

$ sudo sh install_salt.sh -P -M git v2015.8.1

```

**Comment by bytebae** [comment]
Seems to be happening with 2015.5.6 as well:

```
Writing /usr/lib/python2.7/dist-packages/salt-2015.5.6.egg-info
 *  INFO: Running install_debian_git_post()
Created symlink from /etc/systemd/system/multi-user.target.wants/salt-minion.service to /etc/systemd/system/salt-minion.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/salt-master.service to /etc/systemd/system/salt-master.service.
 *  INFO: Running install_debian_check_services()
 *  INFO: Running install_debian_restart_daemons()
Job for salt-master.service failed. See 'systemctl status salt-master.service' and 'journalctl -xn' for details.
 *  INFO: Running daemons_running()
 * ERROR: salt-master was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
 * ERROR: salt-master was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...

```

This is happening with both 

```
$ wget -O install_salt.sh https://bootstrap.saltstack.com/develop
```

and 

```
$ wget -O install_salt.sh https://bootstrap.saltstack.com
```

Something seems to be the matter with restarting daemons in the install script.

**Comment by aanriot** [comment]
Hello,

I noted that it can fail when a previous installation has been run, i.e. through APT.

Have you tried on a fresh system or on one which has been cleaned up?

Best regards,

**Comment by vutny** [comment]
@hubricode I believe this already fixed in latest bootstrap `develop`. Could you please try again?

**Comment by rallytime** [comment]
@hubricode bump - did you get a chance to try this on a newer version? Several releases have come out since this was filed as well as even more work on the `develop` branch as well and I believe this is now fixed.

**Comment by bytebae** [comment]
Yes, this seems fixed now. Thank you for getting back. Cheers!

**Comment by rallytime** [comment]
@hubricode Awesome! I'll close this then. Thanks for confirming.

**Comment by calebwoofenden** [comment]
I'm seeing this problem when I try to add a private repo as an ext_pillar in the master config file. I have one non-private repo structured like this:

```
ext_pillar:
   - git:
     - master https://myorg.com/myrepo.git:
       - root: pillar
```

and things work fine, but when I add a private repo like so:
```
ext_pillar:
   - git:
     - master https://myorg.com/myrepo.git:
       - root: pillar
     - master https://myorg.com/myprivaterepo.git:
       - root: pillar
       - user: myuser
       - password: mypass
```
I get the same error specified in this thread.

EDIT: To add to this, I still get this error if I remove my old ext_pillar and have just the one private repo listed.
